Projeto_LGPD/urls.py
from django.urls import include, path
from django.conf import settings


type_env = f'-{settings.TYPE_ENV}' if settings.TYPE_ENV != 'prod' else ''
PATH_ROOT = f'{settings.PROJECT_NAME}{type_env}/'

urlpatterns = [
    path(PATH_ROOT, include('contas.urls')),
    path(PATH_ROOT + 'accounts/', include('auth_usermanager.urls'))
]

contas/urls.py
from django.urls import path
from contas import views

app_name = 'contas'

urlpatterns = [
    path('', views.home, name='home'),
    path('categorias/', views.categorias, name='categorias'),
    path('assuntos/', views.assuntos, name='assuntos'),
    path('questoes/', views.questoes, name='questoes'),
    path('respostas/', views.respostas, name='respostas'),
    path('atribuicao/', views.atribuicao, name='atribuicao'),
    path('criar_atribuicao/<int:pk>/', views.criaratribuicao, name='form_atribuicao'),
    path('respostas_search/', views.respostas_search, name='respostas_search'),
    path('criar_categoria/', views.criarcategoria, name='criar_categoria'),
    path('criar_assunto/', views.criarassunto, name='criar_assunto'),
    path('criar_questao/', views.criarquestao, name='form_questao'),
    path('criar_resposta/<int:questao_id>/', views.criarresposta, name='form_resposta'),
    path('apagar_categoria/<int:pk>/', views.apagarcategoria, name='apagar_categoria'),
    path('apagar_assunto/<int:pk>/', views.apagarassunto, name='apagar_assunto'),
    path('apagar_questao/<int:pk>/', views.apagarquestao, name='apagar_questao'),
    path('apagar_resposta/<int:pk>/', views.apagarresposta, name='apagar_resposta'),
    path('apagar_atribuicao/<int:pk>/', views.apagaratribuicao, name='apagar_atribuicao'),
    path('editar_categoria/<int:pk>/', views.editarcategoria, name='editar_categoria'),
    path('editar_assunto/<int:pk>/', views.editarassunto, name='editar_assunto'),
    path('editar_questao/<int:pk>/', views.editarquestao, name='editar_questao'),
    path('editar_resposta/<int:pk>/', views.editarresposta, name='editar_resposta'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

core/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TCMRJ - Gerenciador do Questionário da Lei Geral de Proteção de Dados</title>
  <meta name="author" content="Tribunal de Contas do Município do Rio de Janeiro" />
  <meta name="description" content="Portal do Servidor - TCMRJ" />
  <meta name="google" content="notranslate" />
  <meta name="format-detection" content="telephone=no" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/CSS_Adicional_PortalServidor.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'css/etcmfonts.css' %}"> -->
  <link rel="stylesheet" href="{% static 'css/styles__ltr.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  {% block css %}{% endblock css %}
</head>

<body class="ajuste-por-causa-de-navbar-fixed-top">
  <div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="{% url 'contas:home' %}">
        <img src="{% static 'images/tcmrj.png' %}" width="150" class="imgTCMRJ img-fluid" />
        <span id="DesapareceMobile">
          Gerenciador do Questionário da Lei Geral de Proteção de Dados
        </span>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav scrollhide" id="exampleAccordion">
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Informações Financeiras">
            <a class="nav-link nav-link-collapse" data-toggle="collapse" href="#collapseInfoFinanceiras" data-parent="#exampleAccordion" aria-expanded="true">
              <i class="fa fa-fw fa-dollar-sign"></i>
              <span class="nav-link-text">Gestão de Dados</span>
            </a>
            <ul class="sidenav-second-level collapse show" id="collapseInfoFinanceiras">
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Informe de Rendimentos" style="width:253px">
                <a href="{% url 'contas:respostas_search' %}">
                  <i class="fa fa-fw fa-receipt"></i>
                  <span class="nav-link-text">Consulta do Questionário</span>
                </a>
              </li>
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Informações Financeiras">
                <a href="{% url 'contas:categorias' %}">
                  <i class="fa fa-fw fa-receipt"></i>
                  <span class="nav-link-text">Categorias</span>
                </a>
              </li>
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Informações Financeiras">
                <a href="{% url 'contas:assuntos' %}">
                  <i class="fa fa-fw fa-receipt"></i>
                  <span class="nav-link-text">Assuntos</span>
                </a>
              </li>
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Informe de Rendimentos" style="width:253px">
                <a href="{% url 'contas:questoes' %}">
                  <i class="fa fa-fw fa-receipt"></i>
                  <span class="nav-link-text">Questões</span>
                </a>
              </li>
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Informe de Rendimentos" style="width:253px">
                <a href="{% url 'contas:respostas' %}">
                  <i class="fa fa-fw fa-receipt"></i>
                  <span class="nav-link-text">Respostas</span>
                </a>
              </li>       
            </ul>
          </li>

          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Site do TCMRJ">
            <a class="nav-link" href="http://www.tcm.rj.gov.br/WEB/Site/Destaques.aspx">
              <i class="fa fa-fw fa-home fonteMenuPrincipal"></i>
              <span class="nav-link-text fonteMenuPrincipal">Site TCMRJ</span>
            </a>
          </li>
        </ul>

        <!-- Botão de redução no NAV lateral -->
        <ul class="navbar-nav sidenav-toggler">
          <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
              <i class="fa fa-fw fa-angle-left"></i>
            </a>
          </li>
        </ul>

        <!-- Área de Login-->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" style="display:inline" href="#">
              <i class="fa fa-user" style="color: white;"></i> {{user.first_name|title}} - {{user.groups.all.0}}
            </a>
            <a class="nav-link" style="display:inline" href="{% url 'logout' %}">
              <i class="fa fa-sign-out-alt" aria-hidden="true" style="color: white;"></i> Logout
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <div id="page-wrapper" class="content-wrapper">
      {% block content %}
      {% endblock content %}

      {% if messages %}
        <div class="messages toast-container"  id="toastPlacement">
        {% for message in messages %}
            <div class="toast align-items-center text-white bg-{{ message.tags }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ message|safe }}
                    </div>
                    <i type="button" class="btn-close fa fa-times btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close" style="padding-right: 5px;"></i>
                </div>
            </div>      
        {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="{% static 'js/base.js' %}"></script>
  <script>
  $(document).ready(function() {
    $('.toast').toast({
        delay: 5000
    });
    $('.toast').toast('show');
  });
  </script>
  {% block js %}{% endblock js %}
</body>

<footer id="rodape" class="content-wrapper container">
    <div class="row justify-content-center">
        <p>
          Copyright &copy; 2021 - Secretaria de Tecnologia da Informação / Coordenadoria de Informações Estratégicas e Gerenciais - (21) 3824-3639.
        </p>
    </div>
</footer>

</html>

core/templates/navbar.html
{% load static %}

<head>
  <meta charset="UTF-8">
  <title>Gerenciamento do Questionário da Lei Geral de Proteção de Dados</title>
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous"
  >
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="icon" href="{% static 'images/favicon.ico' %}" />
  <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/CSS_Adicional_PortalServidor.css' %}">
  <link rel="stylesheet" href="{% static 'css/etcmfonts.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles__ltr.css' %}">
  <script src="https://www.google.com/recaptcha/api.js?render=6LcmBNQZAAAAAC-1xxTSulDhU6Evy9VHNLUuwuA-"></script>
</head>

<body class="ajuste-por-causa-de-navbar-fixed-top">
  <div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/tcmrj.png' %}" width="150" class="imgTCMRJ img-fluid" />
        <span id="DesapareceMobile">
          Gerenciamento do Questionário da Lei Geral de Proteção de Dados
        </span>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    </nav>


  </div>

     <div>

</div>
</body>