Projeto_LGPD/urls.py
from django.urls import include, path
from django.conf import settings


type_env = f'-{settings.TYPE_ENV}' if settings.TYPE_ENV != 'prod' else ''
PATH_ROOT = f'{settings.PROJECT_NAME}{type_env}/'

urlpatterns = [
    path(PATH_ROOT, include('contas.urls')),
    path(PATH_ROOT + 'accounts/', include('auth_usermanager.urls'))
]

contas/urls.py
from django.urls import path
from contas import views

app_name = 'contas'

urlpatterns = [
    path('', views.home, name='home'),
    path('categorias/', views.categorias, name='categorias'),
    path('assuntos/', views.assuntos, name='assuntos'),
    path('questoes/', views.questoes, name='questoes'),
    path('respostas/', views.respostas, name='respostas'),
    path('atribuicao/', views.atribuicao, name='atribuicao'),
    path('criar_atribuicao/<int:pk>/', views.criaratribuicao, name='form_atribuicao'),
    path('respostas_search/', views.respostas_search, name='respostas_search'),
    path('criar_categoria/', views.criarcategoria, name='criar_categoria'),
    path('criar_assunto/', views.criarassunto, name='criar_assunto'),
    path('criar_questao/', views.criarquestao, name='form_questao'),
    path('criar_resposta/<int:questao_id>/', views.criarresposta, name='form_resposta'),
    path('apagar_categoria/<int:pk>/', views.apagarcategoria, name='apagar_categoria'),
    path('apagar_assunto/<int:pk>/', views.apagarassunto, name='apagar_assunto'),
    path('apagar_questao/<int:pk>/', views.apagarquestao, name='apagar_questao'),
    path('apagar_resposta/<int:pk>/', views.apagarresposta, name='apagar_resposta'),
    path('apagar_atribuicao/<int:pk>/', views.apagaratribuicao, name='apagar_atribuicao'),
    path('editar_categoria/<int:pk>/', views.editarcategoria, name='editar_categoria'),
    path('editar_assunto/<int:pk>/', views.editarassunto, name='editar_assunto'),
    path('editar_questao/<int:pk>/', views.editarquestao, name='editar_questao'),
    path('editar_resposta/<int:pk>/', views.editarresposta, name='editar_resposta'),
]

contas/forms.py
from django import forms
from django.forms import widgets

from .models import Categorias, Assuntos, Questoes, Respostas, QuestoesOrganizationunit
from auth_usermanager.models import OrganizationUnits


class CategoriasForm(forms.ModelForm):
    InputTextWidget = forms.Textarea(attrs={'class': 'form-control'})
    categoria = forms.CharField(required=True, widget=InputTextWidget)
    
    class Meta:
        model = Categorias
        fields = '__all__'

class AssuntosForm(forms.ModelForm):
    TextareaWidget = forms.Textarea(attrs={'class': 'form-control'})
    assunto = forms.CharField(required=True, widget=TextareaWidget)
    
    class Meta:
        model = Assuntos
        fields = '__all__'

class QuestoesForm(forms.ModelForm):

    class Meta:
        model = Questoes
        fields = ('assunto', 'questao')

class QuestoesOrganizationunitForm(forms.ModelForm):
    
    class Meta:
        model = QuestoesOrganizationunit
        fields = ('organization_unit',)

class RespostasForm(forms.ModelForm):
    
    TextareaWidget = forms.Textarea(attrs={'class': 'form-control'})
    
    resposta = forms.CharField(required=True, widget=TextareaWidget)
    comentario = forms.CharField(required=True, widget=TextareaWidget)
    revisado = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'id': 'revisado',
                'class': 'form-check-input'
            }
        )
    )

    class Meta:
        model = Respostas
        fields = (
            'questao',
            'resposta', 
            'comentario', 
            'revisado'           
        )
        widgets = {
            'questao': forms.HiddenInput(),
        }


class RespostasForm_Comite(forms.ModelForm):

    class Meta:
        model = Respostas
        fields = ('comentario_cieg', 'revisado')

class RespostasForm_Usuario_Padrao(forms.ModelForm):

    class Meta:
        model = Respostas
        fields = ('resposta', 'questao')

class RespostasFilterForm(forms.ModelForm):

    class Meta:
        model = Respostas
        fields = ('organization_unit',)

    def __init__(self, *args, **kwargs):
        super(RespostasFilterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control m-2'

class QuestoesFilterForm(forms.ModelForm):

    class Meta:
        model = Questoes
        fields = ('questao',)

    def __init__(self, *args, **kwargs):
        super(QuestoesFilterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control m-2'

contas/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from .filters import RespostasFilter
from .forms import (
    CategoriasForm,
    AssuntosForm, 
    QuestoesForm, 
    RespostasForm, 
    QuestoesOrganizationunitForm, 
    RespostasForm_Comite, 
    RespostasForm_Usuario_Padrao
)

from .models import (
    Categorias, 
    Assuntos, 
    Questoes, 
    Respostas, 
    QuestoesOrganizationunit
)
import datetime
from auth_usermanager.decorators import login_required, permission_required
from django.contrib import messages


@login_required
def home(request):
    return render(request, 'core/home.html')

@login_required
@permission_required('contas.view_categorias', raise_exception=True)
def categorias(request):
    categorias = Categorias.objects.all()
    search = request.GET.get('search')
    if search:
        categorias = categorias.filter(categoria__icontains=search)
    return render(request, 'contas/categorias.html', {'categorias': categorias})
    
@login_required
@permission_required('contas.view_assuntos', raise_exception=True)
def assuntos(request):
    assuntos = Assuntos.objects.all()
    search = request.GET.get('search')
    if search:
        assuntos = assuntos.filter(assunto__icontains=search)
    return render(request, 'contas/assuntos.html', {'assuntos': assuntos})

@login_required
@permission_required('contas.view_questoes', raise_exception=True)
def questoes(request):
    questoes = Questoes.objects.all()
    search_questao = request.GET.get('search')
    if search_questao:
        questoes = questoes.filter(questao__icontains=search_questao).order_by('assunto__assunto')
    return render(request, 'contas/questoes.html', {'questoes': questoes})

@login_required
@permission_required('contas.view_respostas', raise_exception=True)
def respostas(request):
    template_name = 'contas/status.html'
    respostas_search = Respostas.objects.all()
    respostas_search = RespostasFilter(request.GET, queryset=respostas_search)
    context = {'filter': respostas_search}
    return render(request, template_name, context)

@login_required
@permission_required('contas.view_respostas', raise_exception=True)
def respostas_search(request):
    template_name = 'contas/respostas_search.html'
    respostas_search = Respostas.objects.all()
    respostas_search = RespostasFilter(request.GET, queryset=respostas_search)
    context = {'filter': respostas_search}
    return render(request, template_name, context)

@login_required
@permission_required('contas.add_questoesorganizationutint', raise_exception=True)
def atribuicao(request):
    atribuicao = Questoes.objects.all()
    return render(request, 'contas/atribuicao.html', {'atribuicao': atribuicao})

@login_required
@permission_required('contas.add_questoesorganizationutint', raise_exception=True)
def criaratribuicao(request, pk):
    questao = get_object_or_404(Questoes, pk=pk)
    organization_units_questao = QuestoesOrganizationunit.objects.filter(questao_id=pk)
    organization_units_questao_ids = [ouq.organization_unit.id for ouq in organization_units_questao if organization_units_questao]
    form_atribuicao = QuestoesOrganizationunitForm()
    
    if request.method == 'POST':
        form_atribuicao = QuestoesOrganizationunitForm(request.POST)
        if form_atribuicao.is_valid():
            organization_unit = form_atribuicao.cleaned_data['organization_unit']
            if organization_unit.id not in organization_units_questao_ids:
                questao_organization_unit = QuestoesOrganizationunit.objects.create(
                    questao = questao,
                    organization_unit = organization_unit,
                    ano_pesquisa = datetime.datetime.now().date().year
                )
                questao_organization_unit.save()

        return redirect('contas:form_atribuicao', pk=pk)

    context = {
        'form_atribuicao': form_atribuicao, 
        'questao': questao,
        'organization_units_questao': organization_units_questao
    }
    return render(request, 'contas/form_atribuicao.html', context)

@login_required
@permission_required('contas.add_categorias', raise_exception=True)
def criarcategoria(request):
    form_categoria = CategoriasForm()
    if request.method == 'POST':
        form_categoria = CategoriasForm(request.POST)
        if form_categoria.is_valid():
            form_categoria.save()
            messages.add_message(request, messages.SUCCESS, 'Categoria cadastrada com sucesso!')
        return redirect('contas:categorias')
    context = {'form': form_categoria}
    return render(request, 'contas/form_categoria.html', context)
    
@login_required
@permission_required('contas.add_assuntos', raise_exception=True)
def criarassunto(request):
    form_assunto = AssuntosForm()
    if request.method == 'POST':
        form_assunto = AssuntosForm(request.POST)
        if form_assunto.is_valid():
            form_assunto.save()
            messages.add_message(request, messages.SUCCESS, 'Assunto cadastrado com sucesso!')
        return redirect('contas:assuntos')
    context = {'form': form_assunto}
    return render(request, 'contas/form_assunto.html', context)

@login_required
@permission_required('contas.add_questoes', raise_exception=True)
def criarquestao(request):
    form_questao = QuestoesForm()
    if request.method == 'POST':
        form_questao = QuestoesForm(request.POST)
        if form_questao.is_valid():
            form_questao.save()
        return redirect('contas:questoes')
    context = {'form_questao': form_questao}
    return render(request, 'contas/form_questao.html', context)

@login_required
@permission_required('contas.add_respostas', raise_exception=True)
def criarresposta(request, questao_id):
    
    questao = Questoes.objects.get(pk=questao_id)
    organization_unit = request.user.organization_units.all()[0]
    
    # verifica se questão já foi respondida pelo órgão
    has_resposta = Respostas.objects.filter(
        organization_unit=organization_unit,
        questao = questao
    )
    if has_resposta:
        messages.add_message(request, messages.ERROR, 'Questão já respondida anteriomente!')
        #return redirect('contas:respostas')

    if request.user.groups.all()[0].name == 'Comissão':
        form_resposta = RespostasForm_Comite(request.POST,  initial={'questao': questao_id})
        
    elif request.user.groups.all()[0].name == 'Usuário Padrão':
        form_resposta = RespostasForm_Usuario_Padrao(request.POST, initial={'questao': questao_id})
    else:
        form_resposta = RespostasForm(request.POST or None, initial={'questao': questao_id})

    if request.method == 'POST':
        if form_resposta.is_valid(): 
            resposta = form_resposta.save(commit=False)
            resposta.organization_unit = organization_unit
            resposta.matricula = request.user.id
            resposta.ano = datetime.date.today().year
            resposta.save()

            messages.add_message(request, messages.SUCCESS, 'Resposta cadastrada com sucesso!')
            return redirect('contas:respostas')

    context = {
        'form': form_resposta,
        'questao': questao
    }
    return render(request, 'contas/form_resposta.html', context)


@login_required
@permission_required('contas.delete_categorias', raise_exception=True)
def apagarcategoria(request, pk):
    
    categoria = get_object_or_404(Categorias, pk=pk)
    if request.method == "POST":
        categoria.delete()
        messages.add_message(request, messages.SUCCESS, 'Categoria excluída com sucesso!')
        return redirect('contas:categorias')
    context = {'categoria': categoria}
    return render(request, 'contas/apagar_categoria.html', context)

    
@login_required
@permission_required('contas.delete_assuntos', raise_exception=True)
def apagarassunto(request, pk):
    
    assunto = get_object_or_404(Assuntos, pk=pk)
    if request.method == "POST":
        assunto.delete()
        messages.add_message(request, messages.SUCCESS, 'Assunto excluído com sucesso!')
        return redirect('contas:assuntos')
    context = {'assunto': assunto}
    return render(request, 'contas/apagar_assunto.html', context)


@login_required
@permission_required('contas.delete_questoes', raise_exception=True)
def apagarquestao(request, pk):
    item_questao = Questoes.objects.get(id=pk)
    if request.method == "POST":
        item_questao.delete()
        return redirect('contas:questoes')
    context = {'item_questao': item_questao}
    return render(request, 'contas/apagar_questao.html', context)


@login_required
@permission_required('contas.delete_respostas', raise_exception=True)
def apagarresposta(request, pk):
    item_resposta = Questoes.objects.get(id=pk)
    if request.method == "POST":
        item_resposta.delete()
        return redirect('contas:respostas')
    context = {'item_resposta': item_resposta}
    return render(request, 'contas/apagar_resposta.html', context)

@login_required
@permission_required('contas.delete_questoesorganizationutint', raise_exception=True)
def apagaratribuicao(request, pk):
    questao_organization_unit = QuestoesOrganizationunit.objects.get(id=pk)
    if request.method == "POST":
        questao_organization_unit.delete()
        return redirect('contas:form_atribuicao', pk=questao_organization_unit.questao_id)
    context = {'questao_organization_unit': questao_organization_unit}
    return render(request, 'contas/apagar_atribuicao.html', context)

@login_required
@permission_required('contas.change_categorias', raise_exception=True)
def editarcategoria(request, pk):
    categoria = get_object_or_404(Categorias, id=pk)
    form = CategoriasForm(request.POST or None, instance=categoria)
    if form.is_valid():
        form.save()
        messages.add_message(request, messages.SUCCESS, 'Categoria editada com sucesso!')
        return redirect('contas:categorias')

    context = {'form': form, 'categoria': categoria}

contas/templates/contas/apagar_assunto.html
{% extends 'main.html' %}
{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="card card-body">
        <h3>Confirma a exclusão do assunto?</h3>
        <p>{{ assunto }}</p>
        <br>
        <form action="{% url 'contas:apagar_assunto' assunto.id %}" method="POST">
          {% csrf_token %}
          <a class="btn btn-danger" href="{% url 'contas:assuntos' %}">Cancelar</a>
          <input type="submit" class="btn btn-primary" value="Confirmar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

contas/templates/contas/apagar_categoria.html
{% extends 'main.html' %}
{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="card card-body">
        <h3>Confirma a exclusão da categoria?</h3>
        <p>{{ categoria }}</p>
        <br>
        <form action="{% url 'contas:apagar_categoria' categoria.id %}" method="POST">
          {% csrf_token %}
          <a class="btn btn-danger" href="{% url 'contas:categorias' %}">Cancelar</a>
          <input type="submit" class="btn btn-primary" value="Confirmar">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

contas/templates/contas/apagar_questao.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<br>
<div class="'row">
  <div class="col-md-6">
    <div class="card card-body">
      <h1>Confirma a exclusão do {{ item_questao }} ?</h1>
      <form action="{% url 'contas:apagar_questao' item_questao.id %}" method="POST">
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'contas:questoes' %}">Cancelar</a>
        <input class="btn btn-danger" type="submit" name="Confirmar">
      </form>
    </div>
  </div>
</div>
{% endblock %}

contas/templates/contas/apagar_resposta.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<br>
<div class="'row">
  <div class="col-md-6">
    <div class="card card-body">
      <h1>Confirma a exclusão do {{ item_resposta }} ?</h1>
  <form action="{% url 'contas:apagar_resposta' item_resposta.id %}" method="POST">
    {% csrf_token %}
    <a class="btn btn-warning" href="{% url 'contas:resposta' %}">Cancelar</a>
    <input class="btn btn-danger" type="submit" name="Confirmar">
  </form>
    </div>
  </div>
</div>
{% endblock %}

contas/templates/contas/assuntos.html
{% extends 'main.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-6">
        <form action="." method="GET" class="form-inline">
          <input type="text" id="search" name="search" class='form-control' placeholder="Busca">
          <input type="submit" class="btn btn-primary" style="margin-left:10px" value="Buscar em assuntos">
          <a href="." class="btn btn-link">Limpar</a>
        </form>
    </div>
  </div>
  <br>
  <table class="table table-sm">
    <tr>
      <th>Assuntos</th>
        <th> </th>
        <th> </th>
        <th>
          <a href="{% url 'contas:criar_assunto' %}">
          <span>
            <i class="fas fa-plus" style="color: green"></i>
          </span>
        </th>
    </tr>
    <tbody>
      {% for assunto in assuntos %}
        <tr>
          <td>{{ assunto.assunto }}</td>
          <td></td>
          <td>
            <a href="{% url 'contas:apagar_assunto' assunto.id %}">
            <span>
              <i class="fas fa-trash" style="color: red"></i>
            </span>
          </td>
          <td>
            <a href="{% url 'contas:editar_assunto' assunto.id %}">
            <span>
              <i class="fas fa-edit" style="color: blue"></i>
            </span>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

contas/templates/contas/atribuicao.html
{% extends 'main.html' %}
{% block content %}

<div class="row">

</div>

<div class="container">
      <table class="table table-sm">
        <tr>
          <th>Atribuições de Questões</th>
            <th> </th>
            <th> </th>
            <th>
                <a href="{% url 'contas:form_atribuicao' %}">
				<span>
					<i class="fas fa-plus" style="color: green"></i>
				</span>
                </th>
        </tr>
        <tbody>
          {% for assunto in assuntos %}
            <tr>
              <td>{{ assunto.assunto }}</td>
                <td>
                </td>
                <td>
                    <a href="{% url 'contas:apagar_assunto' assunto.id %}">
				<span>
					<i class="fas fa-trash" style="color: red"></i>
				</span>
     			</td>
                <td>
                    <a href="{% url 'contas:editar_assunto' assunto.id %}">
				<span>
					<i class="fas fa-edit" style="color: blue"></i>
				</span>
			    </td>
                </tr>
                {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

contas/templates/contas/editar_questao.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<h3>Editar Questão</h3>

<form method="POST" action="">
  {% csrf_token %}
  {{ form_quest_editado }}
 <a class="btn btn-warning" href="{% url 'contas:questoes' %}">Cancelar</a>
    <input class="btn btn-danger" type="submit" name="Confirmar">

</form>

{% endblock %}

contas/templates/contas/editar_resposta.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<h3>Editar Resposta</h3>

<form method="POST" action="">
  {% csrf_token %}
  {{ form_resp_editado }}
    <input class="btn btn-danger" type="submit" name="Confirmar">

</form>

{% endblock %}

contas/templates/contas/form_assunto.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      {% if form.assunto.id  %}
        <h3>Editar Assunto</h3>
      {% else %}
        <h3>Criar Assunto</h3>
      {% endif %}
      <form method="POST" action=".">
        {% csrf_token %}
        {% if form.errors or form.assunto.errors %}
          <div class="container">
            <div class="row" id="PainelDeMensagensDeErros">
              <div data-val-headertext="Erro(s):" id="ctl06" class="validation-summary-errors" data-valmsg-summary="true" data-valsummary="true">
                  {{form.non_field_errors}}
                  {{form.assunto.errors}}
              </div>
            </div>
          </div>
        {% endif %}
        <div class="form-group">
          {{ form.assunto.label_tag }}
          {{ form.assunto }}
        </div>
        <br>
        <a class="btn btn-danger" href="{% url 'contas:assuntos' %}">Cancelar</a>
        <input type="submit" class="btn btn-primary" value="Salvar">
      </form>
    </div>
  </div>
</div>
{% endblock %}

contas/templates/contas/form_atribuicao.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<h3>Atribuir Questão aos Órgãos</h3>
<p>Questão: {{ questao }}</p>

<form method="POST" action="">
  {% csrf_token %}
  {{ form_atribuicao }}
 <a class="btn btn-warning" href="{% url 'contas:questoes' %}">Cancelar</a>
    <input class="btn btn-danger" type="submit" name="Confirmar">

</form>
<br><br><br><br>
<div class="container">
    <div class="col-6">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Órgãos</th>
                    <th>Ano Pesquisa</th>
                    <th>Data Criação</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% if organization_units_questao %}
                    {% for organization_unit in organization_units_questao %}
                    <tr>
                        <td>{{ organization_unit.organization_unit.id }}</td>
                        <td>{{ organization_unit.organization_unit.description }}</td>
                        <td>{{ organization_unit.ano_pesquisa }}</td>
                        <td>{{ organization_unit.data_criacao}}</td>
                        <td>
                            <a href="{% url 'contas:apagar_atribuicao' organization_unit.id %}">
                                <span>
                                    <i class="fas fa-trash" style="color: red"></i>
                                </span>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

contas/templates/contas/form_categoria.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      {% if form.categoria.id  %}
        <h3>Editar Categoria</h3>
      {% else %}
        <h3>Criar Categoria</h3>
      {% endif %}
      <form method="POST" action=".">
        {% csrf_token %}
        {% if form.errors or form.categoria.errors %}
          <div class="container">
            <div class="row" id="PainelDeMensagensDeErros">
              <div data-val-headertext="Erro(s):" id="ctl06" class="validation-summary-errors" data-valmsg-summary="true" data-valsummary="true">
                  {{form.non_field_errors}}
                  {{form.categoria.errors}}
              </div>
            </div>
          </div>
        {% endif %}
        <div class="form-group">
          {{ form.categoria.label_tag }}
          {{ form.categoria }}
        </div>
        <br>
        <a class="btn btn-danger" href="{% url 'contas:categorias' %}">Cancelar</a>
        <input type="submit" class="btn btn-primary" value="Salvar">
      </form>
    </div>
  </div>
</div>
{% endblock %}

contas/templates/contas/form_resposta.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h3>Adicionar Resposta</h3>
      <br>
      <p><b>Questão: </b>{{questao.questao}}</p>

      <form method="POST" action=".">
        {% csrf_token %}
        {% if form.errors or form.resposta.errors or form.comentario.errors %}
          <div class="container">
            <div class="row" id="PainelDeMensagensDeErros">
              <div data-val-headertext="Erro(s):" id="ctl06" class="validation-summary-errors" data-valmsg-summary="true" data-valsummary="true">
                  {{form.non_field_errors}}
                  {{form.resposta.errors}}
                  {{form.comentario.errors}}
                  {{form.revisado.errors}}
              </div>
            </div>
          </div>
        {% endif %}
        <div class="form-group">

          {{ form.resposta.label_tag }}
          {{ form.resposta }}

          {{ form.comentario.label_tag }}
          {{ form.comentario }}

        </div>
        <div class="form-check">

          {{ form.revisado }}
          <label class="form-check-label" for="revisado">Revisado</label>

        </div>
        {{ form.questao }}
        <br>
        <input type="submit" class="btn btn-primary" value="enviar">

      </form>
    </div>
  </div>
</div>

{% endblock %}

contas/templates/contas/status.html
{% extends 'main.html' %}

{% block content %}


<div>
  <form method="GET" class="form-inline">
    {{ filter.form.as_p }}
    <button type="submit" class="btn btn-primary">OK</button>
    <div class="form-group">
      <a href="." class="btn btn-link">Limpar</a>
    </div>


  </form>
  <div class="col">
    <hr>
    <table class="table table-sm">
      <thead>
        <tr>
               <th>Questão</th>
          <th>Resposta</th>
                 <th>Editar Resposta</th>
        </tr>
      </thead>
      <tbody>
        {% for resposta in filter.qs %}
        <tr>
                   <td>{{ resposta.questao }}</td>
          <td>{{ resposta.resposta }}</td>
 <td><a href="{% url 'contas:editar_resposta' resposta.id %}"><span>
					<i class="fas fa-edit" style="color: blue"></i>
				</span></td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

contas/templates/contas/teste main.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<div>
    <head>
  <title>Questionário LGPD</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
            {% block css %}{% endblock css %}
</head>
<body>

<div class="container">
  <h2>Questionário</h2>
  <p>Conteúdo completo do questionário. Filtre por órgão, assunto ou questão.</p>
  <table class="table">
    <thead class="thead-dark">
      <tr>
      <th>Assunto</th>
          <th>Órgão</th>
          <th>Questão</th>
          <th>Resposta</th>
          <th>Comentário</th>
          <th>Revisado</th>
          <th>Editar Comentário</th>
           <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <tbody>
        {% for resposta in filter.qs %}
        <tr>
          <td>{{ resposta.questao.assunto }}</td>
          <td>{{ resposta.organization_unit }}</td>
          <td>{{ resposta.questao }}</td>
          <td>{{ resposta.resposta }}</td>
          <td>{{ resposta.comentario }}</td>
          <td>
            {% if resposta.revisado %}
      </tr>
    </tbody>
  </table>